# Generated by Django 4.2 on 2024-03-06 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Название категории')),
                ('description', models.TextField(verbose_name='Описание категории')),
                ('slug', models.SlugField(help_text='Идентификатор страницы для URL; разрешены символы латиницы, цифры, дефис и подчёркивание.', unique=True, verbose_name='Идентификатор')),
            ],
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('headline', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('essence', models.TextField(max_length=400, verbose_name='Краткое описание')),
                ('text', models.TextField(max_length=3000, verbose_name='Текст')),
                ('image', models.ImageField(upload_to='image/', verbose_name='Изображение')),
                ('mode', models.CharField(choices=[('S', 'Single choice'), ('M', 'Multiple choices')], default='S', max_length=1, verbose_name='Режим голосования')),
                ('type', models.CharField(choices=[('P', 'Приватное'), ('O', 'Открытое')], default='O', max_length=2, verbose_name='Тип голосования')),
                ('city', models.CharField(default='Вся Россия')),
                ('status', models.CharField(choices=[('UR', 'На модерации'), ('PB', 'Опубликовано'), ('CP', 'Завершено'), ('RJ', 'Отклонено')], default='UR', max_length=2, verbose_name='Статус')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('category', models.ManyToManyField(to='votes.category', verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='VoteOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=255)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votes.poll')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_voted', models.DateTimeField(auto_now=True)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Голос', to='votes.voteoption')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
